spring:
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: coupon
  datasource:
    url: jdbc:mysql://localhost:3307/coupon
      ?useUnicode=true
      &characterEncoding=utf8
      &serverTimezone=Asia/Seoul
      &useSSL=false
      &allowPublicKeyRetrieval=true
      &rewriteBatchedStatements=true
      &cachePrepStmts=true
      &useServerPrepStmts=true
    username: coupon
    password: coupon1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 2000
      idle-timeout: 30000
      max-lifetime: 1800000
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: create

